#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.example.com/{version}

/hello:
  get:
    description: Returns a friendly greeting to the user.
    responses:
      200:
        body:
          text/plain:
            example: "Hello, World!"